name: Unit Testing
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  install-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: ESLint Cache
        uses: actions/cache@v3
        with:
          path: './.eslintcache'
          key: ${{ runner.os }}-eslintcache-${{ github.ref_name }}-${{ hashFiles('.eslintcache') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: test
        run: yarn test:unit:coverage

  #      - name: SonarCloud Scan
  #        uses: sonarsource/sonarcloud-github-action@master
