name: Sonar Scan
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  install-lint-test-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      # Setup Node environment
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'yarn'
      # Load previous cache
      - name: Install Dependencies
        run: yarn install --immutable
      # Run unit tests with coverage
      - name: test
        run: yarn test:unit:coverage
      # Run Code Analysis Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
